### PR TITLE
[MEN-3090] SSL-termination can be turned off via environment variable

### PR DESCRIPTION
**Pull request by breuerfelix**
ref https://tracker.mender.io/browse/MEN-3090

### CODE REVIEW

**Comment by tranchitella** [comment]
@breuerfelix thank you for your PR, much appreciated.
May I ask you to sign-off your commit using the `-s` option and add a Changelog header, then to force-push your commit?

**Comment by breuerfelix** [comment]
@tranchitella thanks for your fast reply!

how do it add a changelog header ? this is not a git feature right ?

**Comment by tranchitella** [comment]
@breuerfelix 
Just squash your commits into a single one and put in the comit description:

```
Changelog: None
Signed-off-by: Your Name <your@git.email>
```

**Comment by breuerfelix** [comment]
@tranchitella thanks for the hints. Sorry for the mess ! Finally it's all working :) I got everything squased into 1 commit and I resolved conflicts (don't know why tho).

**Comment by tranchitella** [comment]
@breuerfelix thank you, it looks okay, we'll review your PR as soon as possible :)

**Comment by mzedel** [comment]
Thanks for the contribution @breuerfelix! Unfortunately today I didn't get to do an in depth review - I'll do it first thing tomorrow though!

Since you mentioned traefik in the issue, you might be interested in this:  https://github.com/mendersoftware/integration/pull/797. However there I haven't taken the no-ssl approach into account yet. Maybe you see something missing, that you came across while working on this PR or something that should be included to ease running it behind your proxy. But this will likely take a little longer until it finds it's way to production, so your PR is more than welcome 👍.

**Comment by breuerfelix** [comment]
Thank you @mzedel ! no hurry, take your time :)

I just had a look at your mentioned pull request. I guess you making your life way too hard ! You try to substitute the api gateway with traefik. This is really complex because you are defining all the nginx locations and rules via traefik labels.  
The problem: once you change something in the api gateway, you have to mirror these settings it to the traefik labels. The chances are high that this will be forgotten in the future :D

Instead you can do the following:
- wipe out SSL in the Api-Gateway (or having the option to disable it via this PR)
- add an additional service with the traefik image
- expose port 80 and 443 from the traefik image
- do the SSL termination and http to https redirect in the traefik image
- proxy the whole traffic from traeffik to the current api-gateway
- do the same for the storage proxy

pros:
- the current mender setup doesn't get changed
- no other service has to get edited

I will do an example setup with traefik or jwilder/nginx-proxy with lets encrypt companion tomorrow and make another pull request on the integration server. I will also add another nginx file there, which disables SSL termination in the storage proxy aswell.

I think the example will be a way better explanation than the one in this answer :D

After that I would love to discuss about the setup so we can have the best from both versions :)

**Comment by mzedel** [comment]
Regarding your previous comment: 
Oh no my intention with the traefik PR was to just get rid of the API gateway altogether and replace it with traefik, since traefik can do all this on it's own and we can just rely on the off-the-shelve version (+ the lets encrypt handling would come basically for free).
So changing the current mender setup is the explicit target, as I want to get rid of the customized api-gateway if possible, to just rely on traefik - so keeping the config in sync would not be required, the extra storage proxy would go away and the https redirect could be turned off using a label:
e.g. for our device auth service: `- traefik.http.routers.deviceauth.middlewares=redirect-https,devauth` would be set to `- traefik.http.routers.deviceauth.middlewares=devauth` in the `no-ssl` compose file.

**Comment by breuerfelix** [comment]
@mzedel Thanks for the clarify!

That definitely makes sense to me. I never really thought about using traefik or traefik-like tools for such complex stuff. Great idea since they support it, so why not also use it? :)

So basically the changes I did are only a temporary fix. I guess my other PR in the integration setup might be a little too complex because I also provided reverse proxy examples. Would it be better if I try to get the other PR as small as possible because it will change in the near future anyway? :)

**Comment by mzedel** [comment]
With regards to your other PR - that looks a bit more complex than I would like, given that the traefik changes might remove most of it 🙈. But on the other hand: I can not guarantee if or give a firm timeline on when the traefik change will land in master. So I would propose to continue the discussion in the other PR - it won't hurt to get it in IMO.

As we are currently readying the next Mender release there were some changes to the testing framework flowing in, but with these in place the full pipeline succeeded 👍. IMO this should now be ready to get merged. ping @tranchitella maybe?
(The reference pipeline for whoever is reviewing:  https://gitlab.com/Northern.tech/Mender/mender-qa/pipelines/114069910)

**Pull request merged**
