### PR TITLE
nginx access log format changed to json

### PR DESCRIPTION
**Pull request by 0lmi**
Signed-off-by: Oleksandr Miliukov <oleksandr.miliukov@northern.tech>

Changelog: Title

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
Build failure is sporadic, @oleorhagen may know something about that one ;)
Can we make this configurable and none default please?
Other settings are injected though entrypoint script: https://github.com/mendersoftware/mender-api-gateway-docker/blob/master/entrypoint.sh

**Comment by maciejmrowiec** [comment]
@mendersoftware/rndity

**Comment by maciejmrowiec** [comment]
@0lmi PING

**Comment by 0lmi** [comment]
requested functionality added

**Pull request merged**
