### PR TITLE
MEN-4382: Add feature toggle to setup proxy for deviceconfig

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by alfrunes** [comment]
I didn't add proxy routes for `/api/devices/v1/deviceconfig/.*` as I'm not sure if there will be any devices API for this service (at least not in the first iteration).

**Comment by tranchitella** [comment]
@alfrunes yes, we'll have device API too, so let's include it straight away.
Do we really need mender-api-gateway-docker, though? Aren't we (half-way) migrating to Traefik?

**Comment by alfrunes** [comment]
> @alfrunes yes, we'll have device API too, so let's include it straight away.

:+1:

> Do we really need mender-api-gateway-docker, though? Aren't we (half-way) migrating to Traefik?

I guess it doesn't hurt to continue supporting nginx as well?

**Review by tranchitella — APPROVED** [review]
Approving, but this stuff is not going to be tested in integration, right?
I'm not sure it helps, then...

**Pull request merged**
