### PR TITLE
MC-301 ssl_trusted_certificate added.

### PR DESCRIPTION
**Pull request by merlin-northern**
Adding ssl_trusted_certificate for the OCSP validation to work.

 . full description: https://tracker.mender.io/browse/MC-301

ChangeLog:title
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by 0lmi** [comment]
I leave this for @mchalski to take a decision about this.

**Comment by merlin-northern** [comment]
> I leave this for @mchalski to take a decision about this.

@mchalski we can do it here, or only for HM, I guess It does not hurt to have correct verify config everywhere.

**Comment by merlin-northern** [comment]
> > I leave this for @mchalski to take a decision about this.
> 
> @mchalski we can do it here, or only for HM, I guess It does not hurt to have correct verify config everywhere.

@mchalski please comment.

**Comment by mchalski** [comment]
@merlin-northern that's way off my map now - can you simply verify that it doesn't break the default demo/test setup? we have self signed certs there iirc. as I understand it, we're effectively enabling oscp (which was screwed up), not sure if proper CA certs won't be required now.

another thing - this would probably be have to worked into the prod.yml file, and the docs site.

**Comment by merlin-northern** [comment]
> @merlin-northern that's way off my map now - can you simply verify that it doesn't break the default demo/test setup? we have self signed certs there iirc. as I understand it, we're effectively enabling oscp (which was screwed up), not sure if proper CA certs won't be required now.
> 
> another thing - this would probably be have to worked into the prod.yml file, and the docs site.

I can do all those things -- no problem. I only wanted you to express your opinion where to put it (this is my first modification in this place, so I do not have a strong opinion)

**Comment by merlin-northern** [comment]
> @merlin-northern that's way off my map now - can you simply verify that it doesn't break the default demo/test setup? we have self signed certs there iirc. as I understand it, we're effectively enabling oscp (which was screwed up), not sure if proper CA certs won't be required now.
> 
> another thing - this would probably be have to worked into the prod.yml file, and the docs site.

the only thing that I can see with self-signed certs is this:
```
2019/11/13 21:59:04 [warn] 1#1: "ssl_stapling" ignored, no OCSP responder URL in the certificate "/var/www/mendersoftware/cert/cert.crt"
nginx: [warn] "ssl_stapling" ignored, no OCSP responder URL in the certificate "/var/www/mendersoftware/cert/cert.crt"
```

**Comment by merlin-northern** [comment]
> > @merlin-northern that's way off my map now - can you simply verify that it doesn't break the default demo/test setup? we have self signed certs there iirc. as I understand it, we're effectively enabling oscp (which was screwed up), not sure if proper CA certs won't be required now.
> > another thing - this would probably be have to worked into the prod.yml file, and the docs site.
> 
> the only thing that I can see with self-signed certs is this:
> 
> ```
> 2019/11/13 21:59:04 [warn] 1#1: "ssl_stapling" ignored, no OCSP responder URL in the certificate "/var/www/mendersoftware/cert/cert.crt"
> nginx: [warn] "ssl_stapling" ignored, no OCSP responder URL in the certificate "/var/www/mendersoftware/cert/cert.crt"
> ```

but apparently it also shows without this patch, so it seems that it simply does not apply to the case of self-signed certificates at all.

**Pull request merged**
